# Generated by Django 3.1.4 on 2021-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='boost_unable',
            field=models.CharField(default='', max_length=50),
        ),
    ]
